
---
version: '1'

# App (Project) name
name: FX-Sample

# App description
description: FX Testing.

# license
licenses:
  - APACHE LICENSE, VERSION 2.

imports:
  # Importing DataSets from Marketplace.
  '@USName': FXLabs/Common/US-Names

  # SQL Injection Strings
  '@GenericSQLInjections': FXLabs/Common/Generic-SQLInjections
  '@OracleSQLInjections': FXLabs/Common/Oracle-SQLInjections
  '@PostgresSQLInjections': FXLabs/Common/Postgres-SQLInjections
  '@SQLServerSQLInjections': FXLabs/Common/SQLServer-SQLInjections
  '@MySQLSQLInjections': FXLabs/Common/MySQL-SQLInjections

  # No-SQL DB Injection String
  '@MongoDBSQLInjections': FXLabs/Common/MongoDB-SQLInjections

  # Cross-Site Scripting Injection Strings
  '@XSSSQLInjections': FXLabs/Common/XSS


# App environments
environments:
  - name: Stg
    baseUrl: http://stg1.fxlabs.io/api/v1
    # app access credentials
    auths:
      - name: Default
        # authType: Basic, OAuth_2_0, Token
        authType: Basic
        username: username@example.com
        password: mypassword
        # Inject password from FX Vault
        #password: '{{@Vault.FxLabs/Stg-Admin-Pass}}'
      # Used by in-valid credential security workflow.
      - name: INVALID_AUTH
        authType: Basic
        username: username@example.com
        # either username or password or both can be invalid.
        password: invalid-pass
#     - name: QE
#       # base URL
#       baseUrl: http://qe.fxlabs.io/api/v1
#       # app access credentials
#       auths:
#        - name: Default
#          # authType: Basic, OAuth_2_0, Token
#          authType: Basic
#          username: username@example.com
#          password: mypassword
#      #OAuth 2.0 Example
#      - name: Stg
#        authType: OAuth_2_0
#        grantType: password                # (e.g. authorization_code, implicit, client_credentials, password)
#        username: peter@example.com        # Optional - Only applies if grantType == password
#        password: password                 # Optional - Only applies if grantType == password
#        clientId: gigy                     #
#        clientSecret: secret               #
#        id: some-id                        # Optional | unique random string
#        accessTokenUri: http://<>/token    #
#        userAuthorizationUri:              # Optional
#        clientAuthenticationScheme: form   # (e.g. form,header,none,query)
#        authorizationScheme: form          # (e.g. form,header,none,query)
#        scope: read,write
#      #Token Example
#      - name: Stg
#        authType: Token
#        header_1: 'cookie: JWTTOKEN=Token' # (e.g. 1)
#        header_1: 'Authorization: <type> <credentials>' # (e.g. 2)



# Job profiles
jobs:
  - name: Stg
    # refers the the env defined above
    environment: Stg
    tags:
      - V1
    # Bot region
    regions: FXLabs/US_WEST_1
    # 0 15 10 ? * * -> Fire at 10:15am every day
    cron: '0 15 10 ? * *'
    #issueTracker: FxLabs/Stg-GitHub-Bot
#  - name: SANDBOX
#    environment: Stg
#    tags:
#      - SANDBOX
